# Evaluación Final - Python para Ciencia de Datos

**Nombre del Estudiante:** 

**Fecha:** 04/07/2025

**Duración:** 2 horas

---

### **Instrucciones Generales**

1.  **Lea atentamente** cada ejercicio antes de empezar a codificar.
2.  Escriba su código únicamente en las celdas designadas con `# Tu código aquí`.
3.  **Ejecute sus celdas** para asegurarse de que el código funciona y produce el resultado esperado.
4.  Puede consultar la documentación oficial de Python, NumPy, Pandas y Matplotlib. No se permite el uso de foros (Stack Overflow) ni herramientas de IA.
5.  Al finalizar, **guarde el notebook** y súbalo a la plataforma Moodle.

--- 
## Sección 1: Fundamentos de Python (Aprox. 45 minutos) 🐍

### Ejercicio 1: Manipulación de Listas y Funciones

Crea una función que reciba una lista de números. La función debe devolver un **diccionario** con las siguientes claves y valores:
- `mayor`: El número más alto de la lista.
- `menor`: El número más bajo de la lista.
- `suma`: La suma de todos los números.
- `promedio`: El promedio de los números.
- `orden_desc`: La lista ordenada de forma descendente.

In [1]:
def analizar_numeros(lista_numeros):
    mayor = max(lista_numeros)
    menor = min(lista_numeros)
    suma = sum(lista_numeros)
    promedio = suma / len(lista_numeros)
    orden_desc = sorted(lista_numeros, reverse=True)
    
    return {
        'mayor': mayor,
        'menor': menor,
        'suma': suma,
        'promedio': promedio,
        'orden_desc': orden_desc
    }

# Código de prueba
numeros = [15, 42, 8, 97, 23, 5, 60]
resultado = analizar_numeros(numeros)
print(resultado)


{'mayor': 97, 'menor': 5, 'suma': 250, 'promedio': 35.714285714285715, 'orden_desc': [97, 60, 42, 23, 15, 8, 5]}


### Ejercicio 2: Diccionarios y Lógica Condicional

Dado el diccionario de calificaciones, escribe un script que itere sobre él y cree un nuevo diccionario llamado `estado_alumnos`. Este nuevo diccionario debe tener dos claves: `Aprobados` y `Reprobados`. Cada clave debe contener una lista de los nombres de los estudiantes que cumplen esa condición (nota >= 7 para aprobar).

In [2]:
calificaciones = {
    'Ana': 9,
    'Luis': 6.5,
    'Pedro': 8,
    'Marta': 5,
    'Julia': 10,
    'Carlos': 4
}

estado_alumnos = {
    'Aprobados': [],
    'Reprobados': []
}

# Iterar sobre el diccionario de calificaciones
for alumno, calificacion in calificaciones.items():
    if calificacion >= 7:
        estado_alumnos['Aprobados'].append(alumno)
    else:
        estado_alumnos['Reprobados'].append(alumno)

print(estado_alumnos)


{'Aprobados': ['Ana', 'Pedro', 'Julia'], 'Reprobados': ['Luis', 'Marta', 'Carlos']}


--- 
## Sección 2: Análisis de Datos con NumPy (Aprox. 45 minutos) 🔢

### Ejercicio 3: Creación y Operaciones con Arrays

1.  Crea una matriz NumPy de 6x6 con números enteros aleatorios entre 1 y 50.
2.  Calcula e imprime la suma de todos los elementos, el valor promedio de la matriz y la desviación estándar.
3.  Extrae y muestra la tercera columna completa de la matriz (índice 2).

In [3]:
import numpy as np

# 1. Crear una matriz 6x6 con números enteros aleatorios entre 1 y 50
matriz = np.random.randint(1, 51, size=(6, 6))

# 2. Calcular la suma, el promedio y la desviación estándar
suma = np.sum(matriz)
promedio = np.mean(matriz)
desviacion_estandar = np.std(matriz)

# Mostrar los resultados
print(f"Matriz generada:\n{matriz}")
print(f"\nSuma de todos los elementos: {suma}")
print(f"Promedio de los elementos: {promedio}")
print(f"Desviación estándar de los elementos: {desviacion_estandar}")

# 3. Extraer y mostrar la tercera columna (índice 2)
tercera_columna = matriz[:, 2]
print(f"\nTercera columna completa: {tercera_columna}")



Matriz generada:
[[26 43  5 43 24 30]
 [47 28  5 50  3  5]
 [16 42 39 11 35 36]
 [45 36 29 33 10 27]
 [ 3 46  4 22 50  8]
 [50 47 44 18 46 36]]

Suma de todos los elementos: 1042
Promedio de los elementos: 28.944444444444443
Desviación estándar de los elementos: 15.898889626575333

Tercera columna completa: [ 5  5 39 29  4 44]


--- 
## Sección 3: Manipulación de Datos con Pandas (Aprox. 1.5 horas) 🐼


### Ejercicio 4: Carga y Limpieza de Datos

1. Carga el archivo `ventas.csv` en un DataFrame de Pandas.
2. Muestra las primeras 7 filas y un resumen estadístico (`.describe()`).
3. Identifica y cuenta los valores nulos por columna.
4. Rellena los valores nulos de la columna `Ventas` con el promedio de esa misma columna.

In [3]:
import pandas as pd

# Cargar el archivo CSV original
df = pd.read_csv('ventas.csv')

# 1. Mostrar las primeras 7 filas
print("Primeras 7 filas:")
print(df.head(7))

# 2. Mostrar resumen estadístico
print("\nResumen estadístico:")
print(df.describe())

# 3. Identificar y contar valores nulos
print("\nValores nulos por columna:")
print(df.isnull().sum())

# 4. Rellenar valores nulos en Ventas con el promedio
ventas_promedio = df['Ventas'].mean()
df['Ventas'] = df['Ventas'].fillna(ventas_promedio)

print("\nDataFrame después de limpieza:")
print(df)

# Opcional: Guardar el dataframe limpio
df.to_csv('ventas_procesado.csv', index=False)

FileNotFoundError: [Errno 2] No such file or directory: 'ventas.csv'

### Ejercicio 5: Filtrado y Agrupación de Datos

Usando el DataFrame del ejercicio anterior:
1. Filtra y muestra todas las ventas realizadas en la ciudad de "Quito".
2. Calcula el total de ventas (`Ventas`) por cada `Producto`.
3. Agrupa los datos por `Ciudad` y `Producto` y calcula el promedio de `Ventas`.

In [ ]:
# 1. Filtrar ventas en Quito
# Tu código aquí


# 2. Calcular total de ventas por producto
# Tu código aquí


# 3. Agrupar por ciudad y producto
# Tu código aquí


### Ejercicio 6: Creación de Nuevas Columnas

1. Crea una nueva columna llamada `Ganancia` que sea la resta de `Ventas` - `Costo`.
2. Encuentra y muestra la fila completa de la venta que generó la **mayor ganancia**.

In [ ]:
# 1. Crear la columna Ganancia
# Tu código aquí


# 2. Encontrar la mayor ganancia
# Tu código aquí


--- 
## Sección 4: Visualización de Datos con Matplotlib (Aprox. 1 hora) 📊

### Ejercicio 7: Gráfico de Barras

Crea un gráfico de barras que muestre el total de ventas (`Ventas`) por `Ciudad`. 
Asegúrate de que el gráfico tenga:
- Un título: "Total de Ventas por Ciudad".
- Una etiqueta para el eje X: "Ciudad".
- Una etiqueta para el eje Y: "Total Ventas".

In [ ]:
import matplotlib.pyplot as plt

# Primero, calcula los datos a graficar (total de ventas por ciudad)
# Tu código aquí
ventas_por_ciudad = None

# Ahora, crea el gráfico de barras
# Tu código aquí

plt.show()

### Ejercicio 8: Gráfico de Líneas

1. Convierte la columna `Fecha` del DataFrame a formato `datetime`.
2. Ordena el DataFrame por fecha de más antigua a más reciente.
3. Crea un gráfico de líneas que muestre la evolución de las `Ventas` a lo largo del tiempo. 
4. Personaliza el gráfico con un título, etiquetas para los ejes y marcadores en cada punto de datos.

In [ ]:
# 1. Convertir columna a datetime
# Tu código aquí


# 2. Ordenar DataFrame por fecha
# Tu código aquí


# 3. Crear el gráfico de líneas
# Tu código aquí


plt.show()